/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/eventos/new` | `/eventos/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/grupos` | `/grupos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/grupos/new` | `/grupos/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil/edit` | `/perfil/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login.styles` | `/login.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/componentes/ModalSelecionarGrupo`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/feed` | `/feed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/eventos/new` | `/eventos/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/grupos` | `/grupos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/grupos/new` | `/grupos/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/perfil/edit` | `/perfil/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login.styles` | `/login.styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/componentes/ModalSelecionarGrupo`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/feed${`?${string}` | `#${string}` | ''}` | `/feed${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/eventos/new${`?${string}` | `#${string}` | ''}` | `/eventos/new${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/grupos${`?${string}` | `#${string}` | ''}` | `/grupos${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/grupos/new${`?${string}` | `#${string}` | ''}` | `/grupos/new${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/perfil/edit${`?${string}` | `#${string}` | ''}` | `/perfil/edit${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login.styles${`?${string}` | `#${string}` | ''}` | `/login.styles${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/componentes/ModalSelecionarGrupo${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/eventos/new` | `/eventos/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/grupos` | `/grupos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/grupos/new` | `/grupos/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil/edit` | `/perfil/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login.styles` | `/login.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/componentes/ModalSelecionarGrupo`; params?: Router.UnknownInputParams; };
    }
  }
}
