/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarContaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarEventoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarGrupoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/EditarPerfil`; params?: Router.UnknownInputParams; } | { pathname: `/EsqueceuSenha`; params?: Router.UnknownInputParams; } | { pathname: `/Feed`; params?: Router.UnknownInputParams; } | { pathname: `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/feedStyle`; params?: Router.UnknownInputParams; } | { pathname: `/grupos`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CriarContaScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CriarEventoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CriarGrupoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/EditarPerfil`; params?: Router.UnknownOutputParams; } | { pathname: `/EsqueceuSenha`; params?: Router.UnknownOutputParams; } | { pathname: `/Feed`; params?: Router.UnknownOutputParams; } | { pathname: `/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/feedStyle`; params?: Router.UnknownOutputParams; } | { pathname: `/grupos`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CriarContaScreen${`?${string}` | `#${string}` | ''}` | `/CriarEventoScreen${`?${string}` | `#${string}` | ''}` | `/CriarGrupoScreen${`?${string}` | `#${string}` | ''}` | `/EditarPerfil${`?${string}` | `#${string}` | ''}` | `/EsqueceuSenha${`?${string}` | `#${string}` | ''}` | `/Feed${`?${string}` | `#${string}` | ''}` | `/Perfil${`?${string}` | `#${string}` | ''}` | `/feedStyle${`?${string}` | `#${string}` | ''}` | `/grupos${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarContaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarEventoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarGrupoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/EditarPerfil`; params?: Router.UnknownInputParams; } | { pathname: `/EsqueceuSenha`; params?: Router.UnknownInputParams; } | { pathname: `/Feed`; params?: Router.UnknownInputParams; } | { pathname: `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/feedStyle`; params?: Router.UnknownInputParams; } | { pathname: `/grupos`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
