/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarContaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarEventoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarGrupoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/componentes/Avatar`; params?: Router.UnknownInputParams; } | { pathname: `/src/componentes/Contato`; params?: Router.UnknownInputParams; } | { pathname: `/src/componentes/Formulario`; params?: Router.UnknownInputParams; } | { pathname: `/src/tipos/types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CriarContaScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CriarEventoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CriarGrupoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/src/componentes/Avatar`; params?: Router.UnknownOutputParams; } | { pathname: `/src/componentes/Contato`; params?: Router.UnknownOutputParams; } | { pathname: `/src/componentes/Formulario`; params?: Router.UnknownOutputParams; } | { pathname: `/src/tipos/types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CriarContaScreen${`?${string}` | `#${string}` | ''}` | `/CriarEventoScreen${`?${string}` | `#${string}` | ''}` | `/CriarGrupoScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/src/componentes/Avatar${`?${string}` | `#${string}` | ''}` | `/src/componentes/Contato${`?${string}` | `#${string}` | ''}` | `/src/componentes/Formulario${`?${string}` | `#${string}` | ''}` | `/src/tipos/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarContaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarEventoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CriarGrupoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/componentes/Avatar`; params?: Router.UnknownInputParams; } | { pathname: `/src/componentes/Contato`; params?: Router.UnknownInputParams; } | { pathname: `/src/componentes/Formulario`; params?: Router.UnknownInputParams; } | { pathname: `/src/tipos/types`; params?: Router.UnknownInputParams; };
    }
  }
}
